apiVersion: v1
kind: Namespace
metadata:
  name: agentic-net-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agentic-net-gw-controller-sa
  namespace: agentic-net-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agentic-net-gw-controller-role
rules:
  # Permissions for reconciling Core/Gateway API/Agentic Networking resources
  - apiGroups: [""]
    resources: ["namespaces", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gatewayclasses", "gateways", "httproutes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gatewayclasses/status", "gateways/status", "httproutes/status"]
    verbs: ["update", "patch"]
  - apiGroups: ["agentic.prototype.x-k8s.io"]
    resources: ["xbackends", "xaccesspolicies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["agentic.prototype.x-k8s.io"]
    resources: ["xbackends/status", "xaccesspolicies/status"]
    verbs: ["update", "patch"]
  # Permissions for managing resources for Envoy deployment
  - apiGroups: [""]
    resources: ["serviceaccounts", "configmaps", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agentic-net-gw-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agentic-net-gw-controller-role
subjects:
  - kind: ServiceAccount
    name: agentic-net-gw-controller-sa
    namespace: agentic-net-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  # TODO: This ClusterRoleBinding needs to be removed after mTLS support is added, which is tracked in https://github.com/kubernetes-sigs/kube-agentic-networking/issues/46
  name: system:service-account-issuer-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:service-account-issuer-discovery
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:unauthenticated
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:authenticated
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentic-net-gw-controller
  namespace: agentic-net-system
  labels:
    app: agentic-net-gw-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agentic-net-gw-controller
  template:
    metadata:
      labels:
        app: agentic-net-gw-controller
    spec:
      serviceAccountName: agentic-net-gw-controller-sa
      containers:
        - name: manager
          image: us-central1-docker.pkg.dev/k8s-staging-images/agentic-net/agentic-networking-controller:main
          imagePullPolicy: Always
          command:
            - "/agentic-net-controller"
          args:
            - "--proxy-image=envoyproxy/envoy:v1.36-latest"
            - "--worker-count=6"
            - "--v=5" # Set log level to 5 (debug)
  revisionHistoryLimit: 1
---
apiVersion: v1
kind: Service
metadata:
  name: agentic-net-xds-server
  namespace: agentic-net-system
spec:
  ports:
    - name: grpc-xds
      port: 15001
      protocol: TCP
      targetPort: 15001
  selector:
    app: agentic-net-gw-controller
  type: ClusterIP
